name: First Workflow
on: workflow_dispatch

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: print greetings 
        run: echo "good day!"
      - name: linux cmd's
        run: |
            ls
            pwd
            ps
