name: First Workflow
on: push    # repository_dispatch,schedule,workflow_call,workflow_dispatch

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings 
        run: echo "${{ toJSON(github) }}"
